postgresql:
  url: postgresql://user:password@localhost:5432/commissar
esi:
  client_id: bm90aGluZyB0byBzZWUgaGVyZQ
  client_secret: bm90aGluZyB0byBzZWUgaGVyZQ
  scopes:
  - publicData
  callback_url: https://anax-rho.space/commissar/callback
  callback_host: anax-rho.space
app:
  hostname: 0.0.0.0
  port: 8080